### ISSUE TITLE
utils_TRFR.metrics等组件缺失

### ISSUE THREAD

**Issue by RunpuWei** [CathyS1996/TRFRNet#1]
代码内import的utils_TRFR.metrics、utils_TRFR.comm、utils_TRFR.loss、utils_TRFR.metrics等均无法找到，请问是不是忘记上传了？

**Comment by wh-isper** [comment]
看commits记录，之前是上传了util这些代码的，然后又删掉了，到现在都没有补上，估计是实验数据有问题

**Comment by CathyS1996** [comment]
是的，之前上传的时候是有的，可能是上次想更新一下，结果不小心把整个删掉了，可以看一下上一个历史版本Jun 7 2022，里面里有utils。
<img width="532" alt="image" src="https://user-images.githubusercontent.com/107036992/210483500-ce7dee77-b58f-414e-823b-fa784f35a735.png">
